import type { Assumption } from "@/lib/assumptions/registry";
import type { Finding } from "./experiment";

export type FindingsIndex = Record<string, { findings: Record<string, Finding> }>;

export interface TripwireState {
  assumption: Assumption;
  state: "tripped" | "clear" | "not-yet-evaluable" | "qualitative";
  observed: Finding | undefined;
}

/** Evaluate every machine-checkable tripwire against current experiment findings. */
export function evaluateTripwires(assumptions: Assumption[], index: FindingsIndex): TripwireState[] {
  return assumptions.map((assumption) => {
    const check = assumption.tripwire.check;
    if (!check) return { assumption, state: "qualitative", observed: undefined };
    const observed = index[check.experiment]?.findings[check.finding];
    if (typeof observed !== "number") return { assumption, state: "not-yet-evaluable", observed };
    const tripped = check.comparison === ">" ? observed > check.threshold : observed < check.threshold;
    return { assumption, state: tripped ? "tripped" : "clear", observed };
  });
}

export function renderTripwires(states: TripwireState[]): string {
  const order = { tripped: 0, "not-yet-evaluable": 1, clear: 2, qualitative: 3 } as const;
  const sorted = [...states].sort((a, b) => order[a.state] - order[b.state] || a.assumption.id.localeCompare(b.assumption.id));
  return [
    "# Assumption tripwires",
    "",
    "Generated by `npm run experiment` from `src/lib/assumptions/registry.ts` and current experiment findings.",
    "A tripped wire does not change a coefficient automatically. It means the evidence named in advance now says the assumption must be reconsidered, and the reconsideration should be recorded.",
    "",
    "| assumption | value | basis | state | observed | trigger |",
    "|---|---|---|---|---|---|",
    ...sorted.map(({ assumption: a, state, observed }) => {
      const check = a.tripwire.check;
      const trigger = check ? `${check.experiment} · ${check.finding} ${check.comparison} ${check.threshold}` : a.tripwire.condition;
      return `| \`${a.id}\` | ${a.value} ${a.unit} | ${a.basis} | **${state}** | ${observed ?? "—"} | ${trigger.replace(/\|/g, "\\|")} |`;
    }),
    "",
    "## Why each threshold",
    "",
    ...sorted.map(({ assumption: a }) => `- \`${a.id}\`: ${a.tripwire.basis}`),
    "",
  ].join("\n");
}
