import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AppNav } from "@/components/AppNav";
import { supabase } from "@/integrations/supabase/client";
import type { AnalysisRecord } from "@/lib/types";
import { classifyFloodRisk, riskColor, riskLabel } from "@/lib/absorption";
import { Loader2, MapPin, ArrowRight, GaugeCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { LAND_COVER_META, type LandCoverKey } from "@/lib/types";

const ORDER: LandCoverKey[] = [
  "vegetation",
  "soil",
  "water",
  "buildings",
  "pavement",
];

export default function Dashboard() {
  const [rows, setRows] = useState<AnalysisRecord[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const { data, error } = await supabase
        .from("analyses")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(50);
      if (error) {
        setError(error.message);
        setRows([]);
        return;
      }
      setRows((data ?? []) as unknown as AnalysisRecord[]);
    })();
  }, []);

  return (
    <div className="flex min-h-screen flex-col">
      <AppNav />
      <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8 md:px-6 md:py-12">
        <header className="mb-8 flex items-end justify-between gap-4 flex-wrap">
          <div>
            <h1 className="text-2xl md:text-3xl font-semibold">
              Analysis dashboard
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Public feed of urban resilience scans generated by the platform.
            </p>
          </div>
          <Button asChild>
            <Link to="/analyze">
              New analysis
              <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </header>

        {rows === null && (
          <div className="flex items-center justify-center py-24 text-muted-foreground">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Loading analyses…
          </div>
        )}

        {rows && rows.length === 0 && (
          <div className="rounded-xl border border-dashed border-border p-12 text-center">
            <Sparkles className="mx-auto mb-3 h-6 w-6 text-primary" />
            <h2 className="text-lg font-semibold">No analyses yet</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Be the first to scan a site and populate the public feed.
            </p>
            <Button asChild className="mt-6">
              <Link to="/analyze">Run first analysis</Link>
            </Button>
            {error && (
              <p className="mt-4 text-xs text-destructive">Error: {error}</p>
            )}
          </div>
        )}

        {rows && rows.length > 0 && (
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {rows.map((r) => {
              const risk = classifyFloodRisk(Number(r.absorption_score));
              return (
                <article
                  key={r.id}
                  className="panel rounded-xl border border-border p-5 transition-colors hover:border-primary/40"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <h3 className="truncate text-base font-semibold">
                        {r.name}
                      </h3>
                      <div className="mt-0.5 flex items-center gap-1 text-xs text-muted-foreground">
                        <MapPin className="h-3 w-3" />
                        <span className="truncate">
                          {r.location_label ??
                            `${Number(r.center_lat).toFixed(3)}, ${Number(
                              r.center_lng
                            ).toFixed(3)}`}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <GaugeCircle
                        className={cn("h-4 w-4", riskColor(risk))}
                      />
                      <span className="font-mono text-lg font-semibold">
                        {Number(r.absorption_score).toFixed(0)}
                      </span>
                    </div>
                  </div>

                  {/* Composition bar */}
                  <div className="mt-4 flex h-2 w-full overflow-hidden rounded-full bg-muted">
                    {ORDER.map((key) => {
                      const pct = Number(r.land_cover?.[key] ?? 0);
                      if (pct <= 0) return null;
                      return (
                        <div
                          key={key}
                          style={{
                            width: `${pct}%`,
                            backgroundColor: LAND_COVER_META[key].token,
                          }}
                          title={`${LAND_COVER_META[key].label}: ${pct}%`}
                        />
                      );
                    })}
                  </div>

                  <div className="mt-3 flex items-center justify-between text-xs">
                    <span
                      className={cn(
                        "rounded-full px-2 py-0.5 font-medium border",
                        risk === "low"
                          ? "border-primary/30 bg-primary/10 text-primary"
                          : risk === "moderate"
                          ? "border-warning/30 bg-warning/10 text-warning"
                          : "border-destructive/30 bg-destructive/10 text-destructive"
                      )}
                    >
                      {riskLabel(risk)} risk
                    </span>
                    <span className="text-muted-foreground">
                      {new Date(r.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
