import { useMemo, useState } from "react";
import { useSensorOptics } from "@/lib/sensor-optics-context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Target, MapPin, X, Radio, AlertTriangle, ShieldCheck, Droplets } from "lucide-react";
import type { IoTSensor } from "@/lib/tactical/types";
import type { FlowPath, RiskZone } from "@/lib/simulation-types";
export interface DetectionTarget { id: string; label: string; category: "SENSOR" | "RISK_ZONE" | "FLOW_CHANNEL" | "INFRASTRUCTURE"; coordinates: [number, number]; metricLabel: string; metricValue: string; status: "NORMAL" | "ALERT" | "CRITICAL"; }
interface DetectionOverlayProps { sensors?: IoTSensor[]; riskZones?: RiskZone[]; flowPaths?: FlowPath[]; onSelectTarget?: (target: DetectionTarget) => void; }
const categoryIcon = { SENSOR: Radio, RISK_ZONE: AlertTriangle, FLOW_CHANNEL: Droplets, INFRASTRUCTURE: ShieldCheck };
export function DetectionOverlay({ sensors = [], riskZones = [], flowPaths = [], onSelectTarget }: DetectionOverlayProps) {
  const { detectionOpen, opticConfig } = useSensorOptics(); const [selectedTarget, setSelectedTarget] = useState<DetectionTarget | null>(null);
  const targets = useMemo(() => { const items: DetectionTarget[] = []; sensors.forEach(s => { const depth = s?.stage_height_m ?? s?.reading ?? 0; items.push({ id: s.id, label: s.name || "Sensor", category: "SENSOR", coordinates: s.coordinates || [0, 0], metricLabel: "Water Depth", metricValue: `${Number(depth).toFixed(2)}m`, status: s.status === "critical" ? "CRITICAL" : s.status === "warning" ? "ALERT" : "NORMAL" }); }); riskZones.forEach((rz, i) => { const obj = rz as unknown as Record<string, unknown>; const coords = (obj.polygon as [number, number][]) || (obj.coordinates as [number, number][]) || []; if (coords.length) { const score = typeof obj.risk_score === "number" ? obj.risk_score : rz.level === "severe" ? .9 : rz.level === "high" ? .7 : rz.level === "moderate" ? .4 : .2; items.push({ id: String(obj.id || `rz-${i}`), label: `Inundation Zone #${i + 1}`, category: "RISK_ZONE", coordinates: coords[0], metricLabel: "Inundation Risk", metricValue: `${(score * 100).toFixed(0)}%`, status: score > .7 ? "CRITICAL" : "ALERT" }); } }); flowPaths.slice(0, 3).forEach((fp, i) => { const obj = fp as unknown as Record<string, unknown>; const coords = (obj.points as [number, number][]) || (obj.coordinates as [number, number][]) || []; if (coords.length) { const volume = Number(obj.volume_m3 ?? obj.flow_volume_m3 ?? 0); items.push({ id: String(obj.id || `fp-${i}`), label: `Hydro Flow Vector #${i + 1}`, category: "FLOW_CHANNEL", coordinates: coords[Math.floor(coords.length / 2)] || coords[0], metricLabel: "Discharge", metricValue: `${volume.toFixed(1)} m³`, status: volume > 200 ? "CRITICAL" : "NORMAL" }); } }); return items; }, [sensors, riskZones, flowPaths]);
  if (!detectionOpen || !targets.length) return null; const counts = targets.reduce<Record<string, number>>((a, t) => ({ ...a, [t.category]: (a[t.category] || 0) + 1 }), {}); const [centerLng, centerLat] = targets[0].coordinates;
  const position = (target: DetectionTarget) => ({ left: `${Math.max(8, Math.min(88, 50 + (target.coordinates[0] - centerLng) * 500))}%`, top: `${Math.max(18, Math.min(82, 50 - (target.coordinates[1] - centerLat) * 500))}%` });
  return <div className="absolute inset-0 pointer-events-none z-20 font-mono text-xs overflow-hidden"><div className="pointer-events-auto absolute top-16 left-4 w-64 hud-panel p-3"><div className="flex items-center justify-between border-b border-border pb-2"><span className="flex items-center gap-2 font-bold"><Target className="h-4 w-4 text-primary" /> TARGET ROSTER</span><Badge variant="outline" className="text-[10px]">{targets.length} CONTACTS</Badge></div><div className="flex flex-wrap gap-2 py-2 text-[10px] text-muted-foreground">{Object.entries(counts).map(([key, value]) => <span key={key}>{key.replace("_", " ")} <strong className="text-foreground">{value}</strong></span>)}</div><div className="flex flex-col gap-1 max-h-40 overflow-y-auto">{targets.map(target => { const Icon = categoryIcon[target.category]; return <button key={target.id} onClick={() => setSelectedTarget(target)} aria-pressed={selectedTarget?.id === target.id} className="target-row flex items-center justify-between gap-2 text-left px-2 py-1.5 rounded-sm"><span className="flex items-center gap-2 truncate"><Icon className="h-3.5 w-3.5 shrink-0 text-primary" /><span className="truncate">{target.label}</span></span><Badge variant={target.status === "CRITICAL" ? "destructive" : target.status === "ALERT" ? "secondary" : "outline"} className="text-[9px]">{target.status}</Badge></button>; })}</div></div>{targets.map(target => <button key={target.id} onClick={() => setSelectedTarget(target)} aria-label={`Select ${target.label}`} className={`target-frame pointer-events-auto absolute ${target.status.toLowerCase()}`} style={position(target)}><span>{target.category}</span><strong>{target.metricValue}</strong></button>)}{selectedTarget && <div className="pointer-events-auto absolute top-16 right-4 w-72 hud-panel p-3"><div className="flex items-center justify-between border-b border-border pb-2"><span className="flex items-center gap-2 font-bold"><Target className="h-4 w-4" style={{ color: opticConfig.accentColor }} /> <span className="truncate">{selectedTarget.label}</span></span><Button variant="ghost" size="icon" onClick={() => setSelectedTarget(null)} className="h-6 w-6" aria-label="Close target details"><X /></Button></div><div className="flex flex-col gap-2 py-2 text-[11px] text-muted-foreground"><div className="flex justify-between">Category <Badge variant="outline" className="text-[10px]">{selectedTarget.category}</Badge></div><div className="flex justify-between">Coordinates <span className="text-foreground">{selectedTarget.coordinates[1].toFixed(4)}°, {selectedTarget.coordinates[0].toFixed(4)}°</span></div><div className="flex justify-between">{selectedTarget.metricLabel} <strong className="text-foreground">{selectedTarget.metricValue}</strong></div></div><Button size="sm" onClick={() => onSelectTarget?.(selectedTarget)} className="w-full gap-2 font-mono text-xs"><MapPin /> Focus Target Lock</Button></div>}</div>;
}
