import { useState, useEffect } from "react";
import { useSensorOptics } from "@/lib/sensor-optics-context";
import { latLngToMaidenhead } from "@/lib/sensor-optics";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Crosshair, Volume2, VolumeX, Eye, Terminal, X, Compass, Layers, Activity, Radio, ShieldCheck } from "lucide-react";

interface TacticalHUDProps { lat?: number; lng?: number; zoom?: number; bearing?: number; pitch?: number; surfaceAreaKm2?: number; absorptionScore?: number; compositeRunoffC?: number; locationName?: string; }

export function TacticalHUD({ lat = 40.758, lng = -73.985, zoom = 15, bearing = 0, pitch = 0, surfaceAreaKm2 = 1.25, absorptionScore = 58.4, compositeRunoffC = 0.42, locationName = "Sector 01 — Mannahatta Catchment" }: TacticalHUDProps) {
  const { hudOpen, setHudOpen, opticConfig, cycleMode, soundEnabled, setSoundEnabled, setCommandPaletteOpen, detectionOpen, setDetectionOpen } = useSensorOptics();
  const [timeUtc, setTimeUtc] = useState("");
  useEffect(() => { const update = () => setTimeUtc(`${new Date().toISOString().substring(11, 19)} Z`); update(); const timer = setInterval(update, 1000); return () => clearInterval(timer); }, []);
  if (!hudOpen) return null;
  const maidenhead = latLngToMaidenhead(lat, lng);
  const riskTone = absorptionScore < 40 ? "CRITICAL" : absorptionScore < 65 ? "WATCH" : "STABLE";
  return (
    <div className="fixed inset-0 pointer-events-none z-40 flex flex-col justify-between p-3 md:p-6 select-none font-mono text-xs overflow-hidden">
      <div className="hud-corner hud-corner-tl" style={{ borderColor: opticConfig.accentColor }} /><div className="hud-corner hud-corner-tr" style={{ borderColor: opticConfig.accentColor }} /><div className="hud-corner hud-corner-bl" style={{ borderColor: opticConfig.accentColor }} /><div className="hud-corner hud-corner-br" style={{ borderColor: opticConfig.accentColor }} />
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-60"><div className="relative flex items-center justify-center"><div className="w-24 h-24 rounded-full border border-dashed animate-spin-slow" style={{ borderColor: opticConfig.accentColor }} /><Crosshair className="absolute w-8 h-8" style={{ color: opticConfig.accentColor }} /><div className="absolute top-14 text-[10px] tracking-widest whitespace-nowrap font-bold" style={{ color: opticConfig.accentColor }}>TGT [{lat.toFixed(5)}°, {lng.toFixed(5)}°]</div></div></div>
      <div className="pointer-events-auto flex flex-col md:flex-row md:items-start justify-between gap-3 z-10 hud-panel p-3">
        <div className="flex flex-col gap-2 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="signal-dot rounded-full" /><span className="font-bold text-sm tracking-wider uppercase text-foreground">GEOINT HUD :: {opticConfig.badge}</span><Badge variant="outline" className="font-mono text-[10px]">GRID: {maidenhead}</Badge><Badge variant="secondary" className="font-mono text-[10px] text-primary"><Radio className="mr-1 h-3 w-3" /> LOCAL DATA</Badge></div><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-muted-foreground"><span className="text-foreground font-semibold">RESILIENCE / CATCHMENT SCAN</span><span>{locationName}</span><span className="hud-freshness"><span className="inline-block size-1.5 rounded-full bg-primary mr-1" /> ANALYSIS READY</span></div></div>
        <div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={cycleMode} className="h-8 gap-1.5 font-mono text-xs"><Eye className="h-3.5 w-3.5" style={{ color: opticConfig.accentColor }} /> Optics [{opticConfig.shortcut}]</Button><Button variant="outline" size="sm" onClick={() => setDetectionOpen(v => !v)} className="h-8 gap-1.5 font-mono text-xs"><Layers className="h-3.5 w-3.5" /> Targets [{detectionOpen ? "ON" : "OFF"}]</Button><Button variant="outline" size="sm" onClick={() => setCommandPaletteOpen(v => !v)} className="h-8 gap-1.5 font-mono text-xs"><Terminal className="h-3.5 w-3.5" /> CMD [⌘K]</Button><Button variant="ghost" size="icon" onClick={() => setSoundEnabled(v => !v)} className="h-8 w-8" title={soundEnabled ? "Mute tactical audio" : "Enable tactical audio"}>{soundEnabled ? <Volume2 /> : <VolumeX />}</Button><Button variant="ghost" size="icon" onClick={() => setHudOpen(false)} className="h-8 w-8" aria-label="Close tactical HUD"><X /></Button></div>
      </div>
      <div className="pointer-events-auto flex flex-col md:flex-row md:items-center justify-between gap-3 z-10 hud-panel p-3"><div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><Compass className="h-3.5 w-3.5 text-primary" /> LAT <strong className="text-foreground">{lat.toFixed(5)}°</strong> LNG <strong className="text-foreground">{lng.toFixed(5)}°</strong></span><span className="flex items-center gap-1.5"><Activity className="h-3.5 w-3.5 text-primary" /> ZOOM <strong className="text-foreground">{zoom.toFixed(1)}</strong> BEARING <strong className="text-foreground">{bearing.toFixed(0)}°</strong> PITCH <strong className="text-foreground">{pitch.toFixed(0)}°</strong></span><span className="hidden lg:inline">AREA <strong className="text-foreground">{surfaceAreaKm2.toFixed(2)} km²</strong> · RUNOFF C <strong className="text-foreground">{compositeRunoffC.toFixed(2)}</strong></span></div><div className="flex items-center gap-3 text-[11px] font-bold tracking-wider" style={{ color: opticConfig.accentColor }}><span className="flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5" /> {riskTone}</span><span className="text-muted-foreground font-normal">|</span><span>{timeUtc}</span></div></div>
    </div>
  );
}
