// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-scans.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-scans.ts
var list_scans_default = defineTool({
  name: "list_scans",
  title: "List terrain scans",
  description: "List recent urban terrain scans with their Urban Absorption Score and flood-risk band, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many scans to return."),
    flood_risk: z.enum(["low", "moderate", "high"]).optional().describe("Optional filter by flood-risk band.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, flood_risk }) => {
    let query = supabaseAnon().from("analyses").select(
      "id,name,location_label,center_lat,center_lng,absorption_score,flood_risk,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (flood_risk) query = query.eq("flood_risk", flood_risk);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-scan.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4";
var get_scan_default = defineTool2({
  name: "get_scan",
  title: "Get terrain scan",
  description: "Fetch one terrain scan by id, including land-cover breakdown, absorption score, flood risk and climate-adaptation recommendations.",
  inputSchema: { id: z2.string().uuid().describe("The scan id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await supabaseAnon().from("analyses").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError(`No scan found with id ${id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/tools/find-scans-near.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4";
var EARTH_KM_PER_DEG = 111.32;
var find_scans_near_default = defineTool3({
  name: "find_scans_near",
  title: "Find scans near a location",
  description: "Find terrain scans whose map centre lies within a radius of the given latitude/longitude, sorted by distance.",
  inputSchema: {
    lat: z3.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    lng: z3.number().min(-180).max(180).describe("Longitude in decimal degrees."),
    radius_km: z3.number().min(0.1).max(500).default(25).describe("Search radius in kilometres."),
    limit: z3.number().int().min(1).max(50).default(10).describe("Maximum scans to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lat, lng, radius_km, limit }) => {
    const radius = radius_km ?? 25;
    const latPad = radius / EARTH_KM_PER_DEG;
    const lngPad = radius / (EARTH_KM_PER_DEG * Math.max(Math.cos(lat * Math.PI / 180), 0.01));
    const { data, error } = await supabaseAnon().from("analyses").select(
      "id,name,location_label,center_lat,center_lng,absorption_score,flood_risk,created_at"
    ).gte("center_lat", lat - latPad).lte("center_lat", lat + latPad).gte("center_lng", lng - lngPad).lte("center_lng", lng + lngPad).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const scans = (data ?? []).map((row) => {
      const dLat = (row.center_lat - lat) * EARTH_KM_PER_DEG;
      const dLng = (row.center_lng - lng) * EARTH_KM_PER_DEG * Math.cos(lat * Math.PI / 180);
      return { ...row, distance_km: Math.round(Math.hypot(dLat, dLng) * 100) / 100 };
    }).filter((row) => row.distance_km <= radius).sort((a, b) => a.distance_km - b.distance_km).slice(0, limit ?? 10);
    return {
      content: [{ type: "text", text: JSON.stringify(scans, null, 2) }],
      structuredContent: { scans }
    };
  }
});

// src/lib/mcp/tools/score-land-cover.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4";
import { classifyFloodRisk, computeAbsorptionScore } from "npm:@/lib/absorption";
var score_land_cover_default = defineTool4({
  name: "score_land_cover",
  title: "Score a land-cover mix",
  description: "Compute the Urban Absorption Score (0-100) and flood-risk band for a hypothetical land-cover mix. Percentages should roughly sum to 100.",
  inputSchema: {
    pavement: z4.number().min(0).max(100).describe("Pavement percentage."),
    buildings: z4.number().min(0).max(100).describe("Building rooftop percentage."),
    vegetation: z4.number().min(0).max(100).describe("Vegetation percentage."),
    water: z4.number().min(0).max(100).describe("Open water percentage."),
    soil: z4.number().min(0).max(100).describe("Bare soil percentage.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (cover) => {
    const score = computeAbsorptionScore(cover);
    const risk = classifyFloodRisk(score);
    return {
      content: [
        {
          type: "text",
          text: `Urban Absorption Score: ${score}/100 \u2014 flood risk: ${risk}.`
        }
      ],
      structuredContent: { absorption_score: score, flood_risk: risk }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cognisync-terrain-weaver",
  title: "cognisync-terrain-weaver",
  version: "0.1.0",
  instructions: "Tools for the Urban Resilience Intelligence platform. Terrain scans classify satellite imagery into pavement, buildings, vegetation, water and soil, then derive an Urban Absorption Score (0-100) and a flood-risk band. Use `list_scans` to browse recent scans, `find_scans_near` to search by coordinates, `get_scan` for full detail including climate-adaptation recommendations, and `score_land_cover` to score a hypothetical land-cover mix.",
  tools: [list_scans_default, get_scan_default, find_scans_near_default, score_land_cover_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
